name: Build Qt 6 Angle
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Setup MSVC Developer CMD
        uses: seanmiddleditch/gha-setup-vsdevenv@master

      - name: Check clang-cl version
        shell: cmd
        run: clang-cl --version

      - name: Cache vcpkg
        uses: actions/cache@v4
        id: cache-vcpkg
        with:
          path: vcpkg
          key: ${{ runner.os }}-vcpkg
          restore-keys: |
            ${{ runner.os }}-vcpkg-

      - name: Bootstrap vcpkg
        if: steps.cache-vcpkg.outputs.cache-hit != 'true'
        shell: cmd
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          bootstrap-vcpkg.bat

      - name: Install EGL from vcpkg
        shell: cmd
        run: |
          vcpkg\vcpkg.exe install egl:x64-windows

      - name: Clone Qt 6-for-Angle branch
        run: |
          git clone https://invent.kde.org/dkazakov/qt5 -b kazakov/for-krita/6.8.0 qt5
          cd qt5
          git cherry-pick 1ac0cfaa2631a639768199fb18a0e0fd9163ac6d
          
      - name: Remove MSVC-incompatible `#warning`
        shell: bash
        run: |
          cd qt5
          patch -p0 << 'EOF'
          *** Begin Patch
          *** Update File: qtbase/src/plugins/platforms/windows/qwindowseglcontext.cpp
          @@ #else // EGL_ANGLE_platform_angle
          -#   warning "Building QWindowsEGLStaticContext without ANGLE is not officially supported"
          +    /* warning removed: MSVC does not support this directive */
          *** End Patch
          EOF

      - name: Install Qt
        run: |
          .\init-repository --module-subset=qtbase,qtdeclarative,qtshadertools,qtsvg,qt5compat
          cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="/arch:AVX2" -DQT_BUILD_TESTS=OFF -DQT_BUILD_EXAMPLES=OFF -DFEATURE_egl=ON -DFEATURE_opengl=ON -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake
          cmake --build build
          cmake --install build --prefix ${{ github.workspace }}/qt6

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: qt6-angle
          path: qt6
